#!/usr/bin/env bash
# install nginx to create html pages
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello world" > /var/www/html/index.html
sudo service nginx restart
